name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /smooth_table/
          targetBranch: main
